Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> class Solution:
...     def divide(self, head):
... 
...         even=node()
... 
...         ev=even
... 
...         od=node()
... 
...         odd=od
... 
...         cur=head
... 
...         while cur:
... 
...             if cur.data%2==0:
... 
...                 ev.next=cur
... 
...                 ev=ev.next
... 
...             else:
... 
...                 odd.next=cur
... 
...                 odd=odd.next
... 
...             cur=cur.next
... 
...         odd.next=None
... 
...         ev.next=od.next
... 
